[tool.poetry]
name = "iscoin"
version = "0.1.0"
description = "Starter code for Engineering Track 304 course"
authors = [
    "AMA <axel.amand@hevs.ch>",
    "RIU <murielle.richard@hevs.ch>",
    "AZL <loic.azzalini@hevs.ch>"
]
license = "MIT"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
ipykernel = "^6.29.5"
numpy = "^2.2.3"
scipy = "^1.15.2"
pillow = "^11.1.0"
requests = "^2.32.3"
opencv-python = "^4.11.0.86"
urbasic = {path = "urbasic", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
